export type Language = "Sepedi" | "Sesotho" | "Setswana";
export type Theme =
  | "animals"
  | "lullabies"
  | "numbers"
  | "family"
  | "nature"
  | "everyday"
  | "greeting";
export type AgeRange = "0-2" | "2-4" | "4-6";

export type Video = {
  id: string;
  title: string;
  titleLocal: string;
  language: Language;
  theme: Theme;
  ageRange: AgeRange;
  duration: string;
  description: string;
  youtubeId: string;
  thumbA: string;
  thumbB: string;
};

export const LANGUAGES: Language[] = ["Sepedi", "Sesotho", "Setswana"];
export const THEMES: Theme[] = [
  "animals",
  "lullabies",
  "numbers",
  "family",
  "nature",
  "everyday",
  "greeting",
];
export const AGE_RANGES: AgeRange[] = ["0-2", "2-4", "4-6"];

export const THEME_LABELS: Record<Theme, string> = {
  animals: "Animals",
  lullabies: "Lullabies",
  numbers: "Numbers",
  family: "Family",
  nature: "Nature",
  everyday: "Everyday life",
  greeting: "Greetings",
};

/** Pilot catalog: 10 videos × 3 languages (Sepedi, Sesotho, Setswana). */
export const CATALOG: Video[] = [
  // Sepedi
  {
    id: "nso-01",
    title: "Hello Little One",
    titleLocal: "Dumela Ngwana",
    language: "Sepedi",
    theme: "greeting",
    ageRange: "0-2",
    duration: "2:14",
    description: "A warm morning greeting song for toddlers learning Sepedi.",
    youtubeId: "lTRiuFIWV54",
    thumbA: "#8B4513",
    thumbB: "#E8A87C",
  },
  {
    id: "nso-02",
    title: "Count With Me",
    titleLocal: "Bala Le Nna",
    language: "Sepedi",
    theme: "numbers",
    ageRange: "2-4",
    duration: "3:02",
    description: "Numbers one to ten with playful rhythm in Sepedi.",
    youtubeId: "yCjJyiqpAuU",
    thumbA: "#A0522D",
    thumbB: "#F4C430",
  },
  {
    id: "nso-03",
    title: "Sleep Softly",
    titleLocal: "Robala Gabotse",
    language: "Sepedi",
    theme: "lullabies",
    ageRange: "0-2",
    duration: "4:10",
    description: "A gentle lullaby for bedtime wind-down.",
    youtubeId: "DWcFGMp6c5g",
    thumbA: "#6B3A2A",
    thumbB: "#C47D22",
  },
  {
    id: "nso-04",
    title: "Farm Friends",
    titleLocal: "Diphologolo tša Polase",
    language: "Sepedi",
    theme: "animals",
    ageRange: "2-4",
    duration: "2:48",
    description: "Meet cows, chickens, and goats through song.",
    youtubeId: "XqZsoesa55w",
    thumbA: "#8B5A2B",
    thumbB: "#7CB342",
  },
  {
    id: "nso-05",
    title: "My Family",
    titleLocal: "Lapa la Ka",
    language: "Sepedi",
    theme: "family",
    ageRange: "2-4",
    duration: "2:30",
    description: "Celebrate mama, papa, and siblings in Sepedi.",
    youtubeId: "kJQP7kiw5Fk",
    thumbA: "#B5651D",
    thumbB: "#F5A26F",
  },
  {
    id: "nso-06",
    title: "Rain Song",
    titleLocal: "Koša ya Pula",
    language: "Sepedi",
    theme: "nature",
    ageRange: "4-6",
    duration: "3:20",
    description: "Dance with the rain and learn weather words.",
    youtubeId: "hY7m5jjJ9mM",
    thumbA: "#8B4513",
    thumbB: "#5DADE2",
  },
  {
    id: "nso-07",
    title: "Wash Your Hands",
    titleLocal: "Hlapa Matsogo",
    language: "Sepedi",
    theme: "everyday",
    ageRange: "2-4",
    duration: "1:55",
    description: "A cheerful hygiene song for daily routines.",
    youtubeId: "CTCl6F0oF0k",
    thumbA: "#A0522D",
    thumbB: "#82C91E",
  },
  {
    id: "nso-08",
    title: "Lion and Lamb",
    titleLocal: "Tau le Konyana",
    language: "Sepedi",
    theme: "animals",
    ageRange: "4-6",
    duration: "3:45",
    description: "Story-song about kindness between animals.",
    youtubeId: "9bZkp7q19f0",
    thumbA: "#6B3A2A",
    thumbB: "#E67E22",
  },
  {
    id: "nso-09",
    title: "Stars Above",
    titleLocal: "Dinaledi",
    language: "Sepedi",
    theme: "lullabies",
    ageRange: "0-2",
    duration: "3:55",
    description: "Soft night-sky lullaby with Sepedi phrases.",
    youtubeId: "RgKAFK5djSk",
    thumbA: "#4A2C1A",
    thumbB: "#92400e",
  },
  {
    id: "nso-10",
    title: "Good Morning Sun",
    titleLocal: "Dumela Letšatši",
    language: "Sepedi",
    theme: "greeting",
    ageRange: "2-4",
    duration: "2:05",
    description: "Wake-up song welcoming the day.",
    youtubeId: "fJ9rUzIMcZQ",
    thumbA: "#8B4513",
    thumbB: "#FBBF24",
  },
  // Sesotho
  {
    id: "st-01",
    title: "Good Day",
    titleLocal: "Lumela",
    language: "Sesotho",
    theme: "greeting",
    ageRange: "0-2",
    duration: "2:00",
    description: "Bright Sesotho greeting for little ones.",
    youtubeId: "2Vv-BfVoq4w",
    thumbA: "#7c2d12",
    thumbB: "#0b6e63",
  },
  {
    id: "st-02",
    title: "One Two Three",
    titleLocal: "Nngoe Pedi Tharo",
    language: "Sesotho",
    theme: "numbers",
    ageRange: "2-4",
    duration: "2:50",
    description: "Counting practice with clap-along beats.",
    youtubeId: "09R8_2nJtjg",
    thumbA: "#9a3412",
    thumbB: "#14b8a6",
  },
  {
    id: "st-03",
    title: "Sleep Song",
    titleLocal: "Pina ea Boroko",
    language: "Sesotho",
    theme: "lullabies",
    ageRange: "0-2",
    duration: "4:05",
    description: "Tender Sesotho lullaby for quiet nights.",
    youtubeId: "hTWKbfoikeg",
    thumbA: "#431407",
    thumbB: "#0f766e",
  },
  {
    id: "st-04",
    title: "Animal Friends",
    titleLocal: "Metsoalle ea Liphoofolo",
    language: "Sesotho",
    theme: "animals",
    ageRange: "2-4",
    duration: "3:10",
    description: "Farm and wild animal names in song.",
    youtubeId: "ScMzIvxBSi4",
    thumbA: "#c2410c",
    thumbB: "#0d9488",
  },
  {
    id: "st-05",
    title: "Our Home",
    titleLocal: "Lapeng la Rona",
    language: "Sesotho",
    theme: "family",
    ageRange: "2-4",
    duration: "2:22",
    description: "Celebrate home and family together.",
    youtubeId: "Ks-_Mh1QhMc",
    thumbA: "#ea580c",
    thumbB: "#115e59",
  },
  {
    id: "st-06",
    title: "River Flow",
    titleLocal: "Noka e Phalla",
    language: "Sesotho",
    theme: "nature",
    ageRange: "4-6",
    duration: "3:28",
    description: "Nature words along a flowing river.",
    youtubeId: "tgbNymZ7vqY",
    thumbA: "#9a3412",
    thumbB: "#134e4a",
  },
  {
    id: "st-07",
    title: "Brush Teeth",
    titleLocal: "Hlatsoa Meno",
    language: "Sesotho",
    theme: "everyday",
    ageRange: "2-4",
    duration: "1:42",
    description: "Fun hygiene habit song before bed.",
    youtubeId: "aqz-KE-bpKQ",
    thumbA: "#fb923c",
    thumbB: "#0b6e63",
  },
  {
    id: "st-08",
    title: "Zebra Dance",
    titleLocal: "Motjeko oa Pitsi",
    language: "Sesotho",
    theme: "animals",
    ageRange: "4-6",
    duration: "2:58",
    description: "Energetic animal dance for older kids.",
    youtubeId: "V-_Iru_Y9iw",
    thumbA: "#c2410c",
    thumbB: "#14b8a6",
  },
  {
    id: "st-09",
    title: "Quiet Night",
    titleLocal: "Bosiú bo Khutsitseng",
    language: "Sesotho",
    theme: "lullabies",
    ageRange: "0-2",
    duration: "3:50",
    description: "Whisper-soft lullaby for babies.",
    youtubeId: "3JZ_D3ELwOQ",
    thumbA: "#7c2d12",
    thumbB: "#134e4a",
  },
  {
    id: "st-10",
    title: "Thank You Song",
    titleLocal: "Pina ea Kea Leboha",
    language: "Sesotho",
    theme: "everyday",
    ageRange: "4-6",
    duration: "2:15",
    description: "Gratitude and polite phrases for kids.",
    youtubeId: "LXb3EKWsInQ",
    thumbA: "#ea580c",
    thumbB: "#0f766e",
  },
  // Setswana
  {
    id: "tn-01",
    title: "Hello Friend",
    titleLocal: "Dumela Tsala",
    language: "Setswana",
    theme: "greeting",
    ageRange: "0-2",
    duration: "2:08",
    description: "Friendly Setswana greetings for little voices.",
    youtubeId: "OPf0YbXqDm0",
    thumbA: "#9a3412",
    thumbB: "#e8902a",
  },
  {
    id: "tn-02",
    title: "Five Little Birds",
    titleLocal: "Dinonyane Di Le Tlhanu",
    language: "Setswana",
    theme: "numbers",
    ageRange: "2-4",
    duration: "2:40",
    description: "Counting song with colourful birds.",
    youtubeId: "CevxZvSJLk8",
    thumbA: "#b45309",
    thumbB: "#f59e0b",
  },
  {
    id: "tn-03",
    title: "Rest Now",
    titleLocal: "Ikhutse Jaanong",
    language: "Setswana",
    theme: "lullabies",
    ageRange: "0-2",
    duration: "4:22",
    description: "Calm Setswana lullaby for sleepy evenings.",
    youtubeId: "JGwWNGJdvx8",
    thumbA: "#78350f",
    thumbB: "#c2410c",
  },
  {
    id: "tn-04",
    title: "Jungle Walk",
    titleLocal: "Tsamaya ya Sekgwa",
    language: "Setswana",
    theme: "animals",
    ageRange: "2-4",
    duration: "3:05",
    description: "Animal sounds and names on a fun walk.",
    youtubeId: "kXYiU_JCYtU",
    thumbA: "#92400e",
    thumbB: "#ea580c",
  },
  {
    id: "tn-05",
    title: "Mama and Me",
    titleLocal: "Mma le Nna",
    language: "Setswana",
    theme: "family",
    ageRange: "0-2",
    duration: "2:18",
    description: "Bonding song celebrating caregivers.",
    youtubeId: "YQHsXMglC9A",
    thumbA: "#d97706",
    thumbB: "#f97316",
  },
  {
    id: "tn-06",
    title: "Mountain Song",
    titleLocal: "Pina ya Thaba",
    language: "Setswana",
    theme: "nature",
    ageRange: "4-6",
    duration: "3:12",
    description: "Explore hills, rivers, and sky vocabulary.",
    youtubeId: "09R8_2nJtjg",
    thumbA: "#9a3412",
    thumbB: "#fb923c",
  },
  {
    id: "tn-07",
    title: "Get Dressed",
    titleLocal: "Apara Diaparo",
    language: "Setswana",
    theme: "everyday",
    ageRange: "2-4",
    duration: "1:48",
    description: "Routine song for mornings getting ready.",
    youtubeId: "e-ORhEE9VVg",
    thumbA: "#f59e0b",
    thumbB: "#eab308",
  },
  {
    id: "tn-08",
    title: "Elephant Parade",
    titleLocal: "Mokgantsho wa Tlou",
    language: "Setswana",
    theme: "animals",
    ageRange: "4-6",
    duration: "2:55",
    description: "Big stomping fun with elephant friends.",
    youtubeId: "fKopy74weus",
    thumbA: "#78350f",
    thumbB: "#d97706",
  },
  {
    id: "tn-09",
    title: "Moon Cradle",
    titleLocal: "Bogobe jwa Ngwedi",
    language: "Setswana",
    theme: "lullabies",
    ageRange: "0-2",
    duration: "4:01",
    description: "Soft moonlit lullaby in Setswana.",
    youtubeId: "60ItHLz5WEA",
    thumbA: "#451a03",
    thumbB: "#92400e",
  },
  {
    id: "tn-10",
    title: "Share the Joy",
    titleLocal: "Abelana Boitumelo",
    language: "Setswana",
    theme: "everyday",
    ageRange: "4-6",
    duration: "2:33",
    description: "Song about kindness and sharing toys.",
    youtubeId: "hT_nvWreIhg",
    thumbA: "#b45309",
    thumbB: "#fbbf24",
  },
];

export function getVideoById(id: string): Video | undefined {
  return CATALOG.find((v) => v.id === id);
}

export function filterCatalog(filters: {
  language?: Language | null;
  theme?: Theme | null;
  ageRange?: AgeRange | null;
}): Video[] {
  return CATALOG.filter((v) => {
    if (filters.language && v.language !== filters.language) return false;
    if (filters.theme && v.theme !== filters.theme) return false;
    if (filters.ageRange && v.ageRange !== filters.ageRange) return false;
    return true;
  });
}
